package stream

import (
	"github.com/mbarreca/gosix/api"
	"github.com/mbarreca/gosix/client"
	"github.com/mbarreca/gosix/consumer"
	"github.com/mbarreca/gosix/models"
)

type Stream struct {
	client *client.Client
	c      *consumer.Consumer
}

// Constructor - You *shouldn't* be using this
func New(c *client.Client, consumer *consumer.Consumer) *Stream {
	return &Stream{client: c, c: consumer}
}

// Gets the Streams attached to an ID
// id -> A specific Stream to get
func (s *Stream) Get(id string) (models.Stream, error) {
	resp, err := api.API[models.Stream, models.Get](id, "", models.Stream{}, s.client)
	if err != nil {
		return models.Stream{}, err
	}
	return *resp.(models.Object[models.Stream]).Value, nil
}

// Gets all Stream
func (s *Stream) GetAll() ([]models.Stream, error) {
	resp, err := api.API[models.Stream, models.Get]("", "", models.Stream{}, s.client)
	if err != nil {
		return nil, err
	}
	var ret []models.Stream
	vals := resp.(models.All[models.Stream])
	for _, val := range *vals.Objects {
		ret = append(ret, *val.Value)
	}
	return ret, nil
}

// Create an Stream, leave the ID blank for an autogenerated ID
// id -> ID of the Stream
// value -> Stream Object
func (s *Stream) Create(id string, value models.Stream) error {
	_, err := api.API[models.Stream, models.Create](id, "", value, s.client)
	if err != nil {
		return err
	}
	return nil
}

// Update a Stream
// id -> ID of the Stream
// value -> Stream Object
func (s *Stream) Update(id string, value models.Stream) error {
	_, err := api.API[models.Stream, models.Update](id, "", value, s.client)
	if err != nil {
		return err
	}
	return nil
}

// Delete a Stream
// id -> ID of the Stream
func (s *Stream) Delete(id string) error {
	_, err := api.API[models.Stream, models.Delete](id, "", models.Stream{}, s.client)
	if err != nil {
		return err
	}
	return nil
}
