package proto

import (
	"github.com/mbarreca/gosix/api"
	"github.com/mbarreca/gosix/client"
	"github.com/mbarreca/gosix/consumer"
	"github.com/mbarreca/gosix/models"
)

type Proto struct {
	client *client.Client
	c      *consumer.Consumer
}

// Constructor - You *shouldn't* be using this
func New(c *client.Client, consumer *consumer.Consumer) *Proto {
	return &Proto{client: c, c: consumer}
}

// Gets the Protos attached to an ID
// id -> A specific Proto to get
func (p *Proto) Get(id string) (models.Proto, error) {
	resp, err := api.API[models.Proto, models.Get](id, "", models.Proto{}, p.client)
	if err != nil {
		return models.Proto{}, err
	}
	return *resp.(models.Object[models.Proto]).Value, nil
}

// Gets all Proto
func (p *Proto) GetAll() ([]models.Proto, error) {
	resp, err := api.API[models.Proto, models.Get]("", "", models.Proto{}, p.client)
	if err != nil {
		return nil, err
	}
	var ret []models.Proto
	vals := resp.(models.All[models.Proto])
	for _, val := range *vals.Objects {
		ret = append(ret, *val.Value)
	}
	return ret, nil
}

// Create an Proto, leave the ID blank for an autogenerated ID
// id -> ID of the Proto
// value -> Proto Object
func (p *Proto) Create(id string, value models.Proto) error {
	_, err := api.API[models.Proto, models.Create](id, "", value, p.client)
	if err != nil {
		return err
	}
	return nil
}

// Update a Proto
// id -> ID of the Proto
// value -> Proto Object
func (p *Proto) Update(id string, value models.Proto) error {
	_, err := api.API[models.Proto, models.Update](id, "", value, p.client)
	if err != nil {
		return err
	}
	return nil
}

// Delete a Proto
// id -> ID of the Proto
func (p *Proto) Delete(id string) error {
	_, err := api.API[models.Proto, models.Delete](id, "", models.Proto{}, p.client)
	if err != nil {
		return err
	}
	return nil
}
