package secret

import (
	"github.com/mbarreca/gosix/api"
	"github.com/mbarreca/gosix/client"
	"github.com/mbarreca/gosix/consumer"
	"github.com/mbarreca/gosix/models"
)

type Secret struct {
	client *client.Client
	c      *consumer.Consumer
}

// Constructor - You *shouldn't* be using this
func New(c *client.Client, consumer *consumer.Consumer) *Secret {
	return &Secret{client: c, c: consumer}
}

// Gets the Secrets attached to an ID
// id -> A specific Secret to get
func (s *Secret) Get(id string) (models.Secret, error) {
	resp, err := api.API[models.Secret, models.Get](id, "", models.Secret{}, s.client)
	if err != nil {
		return models.Secret{}, err
	}
	return *resp.(models.Object[models.Secret]).Value, nil
}

// Gets all Secret
func (s *Secret) GetAll() ([]models.Secret, error) {
	resp, err := api.API[models.Secret, models.Get]("", "", models.Secret{}, s.client)
	if err != nil {
		return nil, err
	}
	var ret []models.Secret
	vals := resp.(models.All[models.Secret])
	for _, val := range *vals.Objects {
		ret = append(ret, *val.Value)
	}
	return ret, nil
}

// Create an Secret, leave the ID blank for an autogenerated ID
// id -> ID of the Secret
// value -> Secret Object
func (s *Secret) Create(id string, value models.Secret) error {
	_, err := api.API[models.Secret, models.Create](id, "", value, s.client)
	if err != nil {
		return err
	}
	return nil
}

// Update a Secret
// id -> ID of the Secret
// value -> Secret Object
func (s *Secret) Update(id string, value models.Secret) error {
	_, err := api.API[models.Secret, models.Update](id, "", value, s.client)
	if err != nil {
		return err
	}
	return nil
}

// Delete a Secret
// id -> ID of the Secret
func (s *Secret) Delete(id string) error {
	_, err := api.API[models.Secret, models.Delete](id, "", models.Secret{}, s.client)
	if err != nil {
		return err
	}
	return nil
}
